/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Coneccao;
import java.sql.Connection;


public class App {

    public static void main(String[] args) {
        ConexaoSQLite conexaoSQLite = new ConexaoSQLite();
        Connection conexao = conexaoSQLite.conectar();
                
        if(conexao !=null){
            //criar tabela
            CriarTabela.criarTabelaUsuarios(conexao);
            
            //inserir usuario
            InserirUsuario.inserirUsuario(conexao, "Joao", "Joao@gmail.com");
            InserirUsuario.inserirUsuario(conexao, "Leo", "Leo@gmail.com");
            
            //Listar usuarios
            ListarUsuarios.listarUsuarios(conexao);
            
            //Fechar conexao
            conexaoSQLite.desconectar(conexao);
        }
    }
}
