/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Konoha;

public class App {
    
    public static void main(String[] args) {
        Cla uchiha = new Uchiha("Uchiha","Morto");
        Cla hyuga = new Hyuga("Hiuga","Hinata");
        Cla nara = new Nara("Nara","Shikamaru");
        Cla akimichi = new Akimichi("Akimichi","Choji");
        
        uchiha.habilidadeEspecial();
        uchiha.obterDetalhes();
        
        hyuga.habilidadeEspecial();
        hyuga.obterDetalhes();
        
        nara.habilidadeEspecial();
        nara.obterDetalhes();
        
        akimichi.habilidadeEspecial();
        akimichi.obterDetalhes();
    }
}
